### ISSUE TITLE
Enable searching with ISBN

### ISSUE THREAD

**Issue by srdg** [srdg/goodreadsrec#1]
In `app.py:L17`:  
Change `gc.book(processed_text)` to `gc.book(isbn=processed_text)`.  
This will make the API search for the book with referenced [ISBN number](https://en.m.wikipedia.org/wiki/International_Standard_Book_Number).

**Comment by agarwalBinay18** [comment]
hey,I would like to work on this issue!

**Comment by srdg** [comment]
> 
> 
> hey,I would like to work on this issue!

Please read the pinned message in the discord channel.

**Comment by SuvamPrasd** [comment]
This issue has been fixed and updated.
