### ISSUE TITLE
Create main()

### ISSUE THREAD

**Issue by srdg** [srdg/goodreadsrec#13]
Extract the following code snippet:  
``
if __name__=="__main__":      
	app.run()
``
to a main() method.

**Comment by SubhradeepSS** [comment]
Is the issue about creating a separate file for main or just a separate function named main inside the app.py file?

**Comment by srdg** [comment]
> Is the issue about creating a separate file for main or just a separate function named main inside the app.py file?

Just a separate `main()` in the same file.

**Comment by SubhradeepSS** [comment]
For now,main would contain only app.run()?

**Comment by srdg** [comment]
@SubhradeepSS  yes.

**Comment by srdg** [comment]
Issue resolved.
