### ISSUE TITLE
Enhance the template design 

### ISSUE THREAD

**Issue by srdg** [srdg/goodreadsrec#15]
Make the app look more sleek. Responsive feature must not be compromised with. Other than that, feel free to customize the colours, look, design and user interaction in any way you see fit.

IMPORTANT : Before submitting the PR, take a screenshot/photo/video of your proposed design and post it on the **#goodreadsrec** channel of the [discord server](https://discord.gg/7Eu5kxe). Please wait for approval, on receiving which, you can submit the pull request.

**Comment by SuvamPrasd** [comment]
I am going to make the web app responsive with awesome design.

**Comment by srijande** [comment]
assign me

**Comment by srdg** [comment]
@thesrijande I assigned you since @SuvamPrasd is not working on it anymore. Please make sure you submit a screenshot of your proposed design in the server channel first.
