### ISSUE TITLE
Use rerouting to customize URLs

### ISSUE THREAD

**Issue by srdg** [srdg/goodreadsrec#19]
Use the URL re-routing feature in Flask such that, when the user searches for a book with ISBN no. or the book ID (Ref : #3) the app should reroute the user in the following template:  
`https://goodreadsrec.herokuapp.com/ISBN/<isbn-no>`  
or  
`https://goodreadsrec.herokuapp.com/ID/<id-no>` .

**Comment by SuvamPrasd** [comment]
I am going to start in this issue.
