### ISSUE TITLE
Customize errors instead of generic 404

### ISSUE THREAD

**Issue by srdg** [srdg/goodreadsrec#2]
Currently, exceptions occur in the following breakpoints:  
- [x]  Not enough books (<7) are listed in the `similar_books` API call : results in `IndexError`.
- [x] No recommendations could be found : results in an empty list.
- [x] The `ID/ISBN` search tag is invalid (current 404 page lists this reason to the user).

Include 3 separate error pages (add the `.html` files to `templates` directory) for the three different cases and render the proper templates for each case.

**Comment by SuvamPrasd** [comment]
I am going to work on this issue.
