### ISSUE TITLE
Fix ISBN search 

### ISSUE THREAD

**Issue by srdg** [srdg/goodreadsrec#31]
**The bug**
Searching with any ISBN beginning with 0 crashes the app and redirect to a 404 page.

**To Reproduce**
1. Go to [http://goodreadsrec.herokuapp.com/](http://goodreadsrec.herokuapp.com/).
2. Type in the search box any ISBN of a book starting with 0. For e.g., 0743203046, 0393318281, 0373792689 and select ISBN radio button. Hit Enter/click on Submit.
3. App should redirect to the 404 page.

**Expected behavior**
App should have shown the recommendations.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] NA (any)
 - Browser [e.g. chrome, safari] NA (any)
 - Version [e.g. 22] NA (any)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] NA (any)
 - OS: [e.g. iOS8.1] NA (any)
 - Browser [e.g. stock browser, safari] NA (any)
 - Version [e.g. 22] NA (any)

**Resolution**
The error stems from `app.py:L30` where the information from the text box is stripped and converted to an integer to be stored in `query_num`. Remove the conversion to `int` and keep `query_num` as a string.

**Comment by SuvamPrasd** [comment]
I am going to fix.
