### ISSUE TITLE
Rename variables according to context 

### ISSUE THREAD

**Issue by srdg** [srdg/goodreadsrec#6]
Change the following variable names and all of their references: 
- [x] text ➤ input
- [x]  processed_text ➤ isbn_no/book_id (Ref: #3) 
- [x] links ➤ recommendations

**Comment by ivaibhavjindal** [comment]
I'd like to work on this. Are these changes supposed to be made only in app.py file?

**Comment by SuvamPrasd** [comment]
I have changed the variable names respectively.

**Comment by srdg** [comment]
@ivaibhavjindal the changes are already made - perhaps you'd like to pick another issue. You can also join the official discord channel (link in CONTRIBUTING.md) to receive live updates of who is working on what.
