### ISSUE TITLE
Modularize  code in app.py

### ISSUE THREAD

**Issue by srdg** [srdg/goodreadsrec#7]
Extract a function from `app.py:L17-18` and name it `get_search_tag()` which returns a list of `recommendations`(Ref #6).

Modify it to `get_search_tag(search_by_id<boolean>)` after implementing issue #3.

**Comment by SubhradeepSS** [comment]
I fixed it in PR #23

**Comment by srdg** [comment]
@SubhradeepSS change `if search_by_id() == true:` to `if search_by_id() == True:` and resubmit the PR.

**Comment by srdg** [comment]
@SubhradeepSS also, return a tuple of `(links, query_num)` from  function `get_search_tag()` and extract the `query_num` variable in method `form_post()`.
