### ISSUE TITLE
Update method names in app.py

### ISSUE THREAD

**Issue by srdg** [srdg/goodreadsrec#8]
Update the method names in `app.py` as follows:

+  `my_form_post()` ➤ `form_post()`
+ `my_form()` ➤ `form()`

**Comment by SuvamPrasd** [comment]
Hello sir,
I am going to work on this issue. Shall I enhance the index.html file using CSS transition and javascript?

**Comment by srdg** [comment]
> 
> 
> Hello sir,
> I am going to work on this issue. Shall I enhance the index.html file using CSS transition and javascript?

Could you prepare a demo of what you have in mind and submit it in the discord channel? And please do not call me sir 😅
